#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const HELP = `Usage: node build-preview.mjs [--stdout]

Builds preview.html from catalog.json and every snippet it lists: a gallery where each
asset animates on a mock app screen. Run it after adding or editing an asset.

  --stdout   print the page instead of writing preview.html (the checker uses this)

In the page: Play/Pause, a scrubber that seeks every asset to the same fraction of its own
duration, and window.seekAll(fraction) / window.seekAllTo(seconds) for screenshots.`;

const DIR = import.meta.dirname;
const args = process.argv.slice(2);
if (args.includes("-h") || args.includes("--help")) {
  console.log(HELP);
  process.exit(0);
}

export function buildPreview() {
  const { assets } = JSON.parse(readFileSync(join(DIR, "catalog.json"), "utf8"));
  const cells = assets.map((a) => {
    const html = a.files.find((f) => f.endsWith(".html"));
    const snippet = readFileSync(join(DIR, html), "utf8").trim();
    const fn = a.call.split("(")[0].split(".")[1];
    const opts = JSON.stringify(a.preview_options ?? {});
    return `<figure class="cell" data-fn="${fn}" data-opts='${opts}'>
<div class="frame"><div class="stage">
<div class="mock" aria-hidden="true"><div class="mock-side"></div><div class="mock-main"><div class="mock-bar"></div><div class="mock-row"></div><div class="mock-row"></div><div class="mock-row short"></div><div class="mock-row"></div></div></div>
${snippet}
</div></div>
<figcaption><b>${a.id}</b><span>${a.category}, ${a.default_duration_s} s</span></figcaption>
</figure>`;
  });
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Graphics Kit Preview</title>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
<style>
  :root { --bg: #f3f4f6; --fg: #111418; --muted: #5b6472; --card: #ffffff; --line: #d9dde3; }
  @media (prefers-color-scheme: dark) { :root { --bg: #0b0e12; --fg: #e8ebef; --muted: #9aa3af; --card: #151a21; --line: #262d36; } }
  * { box-sizing: border-box; }
  body { margin: 0; padding: 24px 16px 48px; background: var(--bg); color: var(--fg); font: 15px/1.4 system-ui, sans-serif; }
  header { max-width: 1600px; margin: 0 auto 20px; display: flex; flex-wrap: wrap; gap: 12px 20px; align-items: center; }
  header h1 { margin: 0; font-size: 22px; }
  header p { margin: 0; color: var(--muted); flex-basis: 100%; }
  .controls { display: flex; gap: 12px; align-items: center; flex: 1 1 320px; }
  .controls input { flex: 1; }
  button { font: inherit; padding: 6px 14px; border-radius: 8px; border: 1px solid var(--line); background: var(--card); color: var(--fg); cursor: pointer; }
  main { max-width: 1600px; margin: 0 auto; display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 360px), 1fr)); gap: 18px; }
  .cell { margin: 0; background: var(--card); border: 1px solid var(--line); border-radius: 12px; overflow: hidden; }
  .frame { position: relative; aspect-ratio: 16 / 9; overflow: hidden; }
  .stage { position: absolute; left: 0; top: 0; width: 1920px; height: 1080px; transform-origin: 0 0; transform: scale(var(--s, 0.25)); overflow: hidden; background: #2b3440; }
  figcaption { display: flex; justify-content: space-between; gap: 8px; padding: 8px 12px; }
  figcaption span { color: var(--muted); }
  .mock { position: absolute; inset: 0; display: flex; background: linear-gradient(#e9edf2, #dfe4ea); }
  .mock-side { width: 300px; background: #1f2937; }
  .mock-main { flex: 1; padding: 60px 80px; }
  .mock-bar { height: 70px; width: 60%; margin-bottom: 50px; border-radius: 12px; background: #c3cad4; }
  .mock-row { height: 90px; margin-bottom: 30px; border-radius: 12px; background: #ffffff; box-shadow: 0 2px 6px rgba(0,0,0,.08); }
  .mock-row.short { width: 55%; }
</style>
</head>
<body>
<header>
  <h1>Graphics kit preview</h1>
  <div class="controls">
    <button id="play" type="button">Pause</button>
    <input id="scrub" type="range" min="0" max="1" step="0.001" value="0" aria-label="Seek all assets" />
    <output id="pos">0%</output>
  </div>
  <p>Each asset loops over its default duration on a mock app screen. The scrubber seeks every asset to the same fraction of its own duration. Generated by build-preview.mjs from catalog.json.</p>
</header>
<main>
${cells.join("\n")}
</main>
<script>
  const cells = [...document.querySelectorAll(".cell")].map((cell) => {
    const el = cell.querySelector(".clip");
    const tl = gsap.timeline({ paused: true });
    window.gfx[cell.dataset.fn](tl, el, JSON.parse(cell.dataset.opts));
    return { cell, tl, dur: +el.dataset.duration };
  });
  const fit = () => cells.forEach(({ cell }) => {
    const frame = cell.querySelector(".frame");
    frame.style.setProperty("--s", frame.clientWidth / 1920);
  });
  new ResizeObserver(fit).observe(document.querySelector("main"));
  fit();
  let playing = true;
  let t0 = performance.now();
  let offset = 0;
  window.seekAll = (f) => { playing = false; document.getElementById("play").textContent = "Play"; cells.forEach((c) => c.tl.seek(c.dur * f, false)); document.getElementById("pos").textContent = Math.round(f * 100) + "%"; };
  window.seekAllTo = (s) => { playing = false; document.getElementById("play").textContent = "Play"; cells.forEach((c) => c.tl.seek(Math.min(s, c.dur), false)); };
  document.getElementById("scrub").addEventListener("input", (e) => window.seekAll(+e.target.value));
  document.getElementById("play").addEventListener("click", (e) => {
    playing = !playing;
    e.target.textContent = playing ? "Pause" : "Play";
    t0 = performance.now();
    offset = +document.getElementById("scrub").value;
  });
  const loop = () => {
    if (playing) {
      const s = (performance.now() - t0) / 1000;
      cells.forEach((c) => c.tl.seek((s + offset * c.dur) % (c.dur + 0.6), false));
    }
    requestAnimationFrame(loop);
  };
  requestAnimationFrame(loop);
</script>
</body>
</html>
`;
}

if (process.argv[1] && resolve(process.argv[1]) === import.meta.filename) {
  const page = buildPreview();
  if (args.includes("--stdout")) process.stdout.write(page);
  else {
    writeFileSync(join(DIR, "preview.html"), page);
    console.log("Wrote preview.html");
  }
}
